# Generated by Django 5.2.8 on 2025-12-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(help_text='Уникальный ID пользователя в Telegram (всегда есть)', max_length=100, unique=True, verbose_name='ID Telegram пользователя')),
                ('username', models.CharField(blank=True, help_text='@username (может быть скрыт пользователем)', max_length=100, verbose_name='Юзернейм в Telegram')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя (может быть скрыто)', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя (может быть скрыта)', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона (заполняется при заказе)', max_length=20, verbose_name='Телефон')),
                ('photo_url', models.URLField(blank=True, help_text='Ссылка на аватарку в Telegram (может быть скрыта)', max_length=500, verbose_name='Ссылка на фото профиля')),
                ('is_synced', models.BooleanField(default=False, help_text='Пользователь авторизован через Telegram WebApp', verbose_name='Синхронизирован с Telegram')),
                ('is_active', models.BooleanField(default=True, help_text='Может ли пользователь совершать покупки', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
