# Generated by Django 5.2.8 on 2025-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_product_main_image_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_type',
            field=models.CharField(choices=[('preorder', 'Предзаказ'), ('in_stock', 'Есть на складе')], default='preorder', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
